CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=1800

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Layout Shift (JIS layout support) — roBa と同じ
CONFIG_LAYOUT_SHIFT_TARGET_JIS=y

# 親機を右側にするため、left側は周辺機(peripheral)にする
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
